### ISSUE TITLE
Questions/Feedback

### ISSUE THREAD

**Issue by winkerVSbecks** [c8r/lab#3]
Great work with Lab so far! Had some questions/feedback:

* Is it possible to use JSX in `children` prop? This would allow users to create more complex examples.

* Is it possible to provide default props? Some styles seem to generate this, but it might be helpful to provide defaults for other props too.

* `rem` instead of `px` for units would be a nice.

* Can we specify element `type` as a prop or `is` prop like rebass uses? For example I can’t make a generic heading component. This might be out of scope which is understandable. For now I ended up using `withComponent` https://github.com/winkerVSbecks/triangle-lab-demo/blob/master/src/designSystem/index.js

* I was using Lab with a create-react-app project. CRA doesn't allow imports from outside `src` so, `theme.json` can't be imported. Had to manually copy it into `src`.

* It would be helpful to get some more documentation/examples of importing components. I just wasn't able get that working. `import`, `JSX`, etc. kept breaking it.

**Comment by jxnblk** [comment]
Thanks for all this great feedback! We really appreciate it!

- We're looking into support for JSX-based examples instead of the object syntax, so hopefully that helps with your first question.
- It is possible to expose default props, and we plan to have that UI available in one of the next few releases.
- At the moment, the app only allows for pixel units, but we're also looking into allowing any CSS unit using string values.
- The app doesn't support an `is` prop at the moment, but configurable higher-order-components is on the roadmap.
- When using create-react-app, you should be able to specify the `src` folder for your Lab project. To manually change the location, move both the `theme.json` and `lab.json` files to the desired location. We'll look into allowing for custom folder paths for the configuration files, but hopefully this workaround helps for now.
- We're working on adding more documentation to https://compositor.io/lab/docs/ but here are some things that might help you troubleshoot your problems:
  - If a component fails to load, the preview should display an error to help with debugging.
  - Make sure components are located within the same root folder as your Lab project or in a subdirectory.
  - Make sure any npm dependencies have been installed in your project by running npm install in your terminal.
  - Make sure your component DOES NOT make use of any webpack loaders or other build-specific tools.

Hope that helps, and feel free to ask any further questions if anything doesn't make sense.

**Comment by winkerVSbecks** [comment]
Thank @jxnblk this was super helpful!
